// React/src/App.tsx
import React from 'react';
import DataGrid, { Column, Editing } from 'devextreme-react/data-grid';
import DateBox from 'devextreme-react/date-box';
import { Format } from 'devextreme/localization';
import { employees } from './data';
import { formatter, parser } from './utils';
import './App.css';
import 'devextreme/dist/css/dx.material.blue.light.compact.css';

const now = new Date();

const format: Format = {
  parser: (val) => parser(val),
  formatter: (val) => formatter(val),
};

const editorOptions: { displayFormat: Format } = {
  displayFormat: {
    parser: (val) => parser(val),
    formatter: (val) => formatter(val),
  },
};

function App(): JSX.Element {
  return (
    <div className="main">
      <DateBox
        value={now}
        type="date"
        label="Date with the short year"
        displayFormat={format}
      />
      <DataGrid
        id="grid"
        dataSource={employees}
        width={400}
        keyExpr='ID'
        showBorders={true}
      >
        <Editing mode="cell" allowUpdating={true} />
        <Column dataField='FirstName' />
        <Column dataField="LastName" />
        <Column dataField='BirthDate' dataType='date' editorOptions={editorOptions} />
      </DataGrid>
    </div>
  );
}

export default App;

// Angular/src/app/app.component.ts
import { Component } from '@angular/core';
import { Format } from 'devextreme/localization';
import { formatter, parser } from '../utils';
import { Employee, Service } from './app.service';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
  providers: [Service],
})
export class AppComponent {
  employees: Employee[];

  now: Date = new Date();

  format: Format = {
    parser: (val) => parser(val),
    formatter: (val) => formatter(val),
  };

  editorOptions = {
    displayFormat: this.format,
  };

  constructor(service: Service) {
    this.employees = service.getEmployees();
  }
}

<dx-date-box
  [value]="now"
  type="date"
  [width]="400"
  label="Date with the short year"
  [displayFormat]="format"
>
</dx-date-box>
<dx-data-grid
  id="grid"
  [dataSource]="employees"
  [width]="400"
  keyExpr="ID"
  [showBorders]="true"
>
  <dxo-editing mode="cell" [allowUpdating]="true"></dxo-editing>
  <dxi-column dataField="FirstName"></dxi-column>
  <dxi-column dataField="LastName"></dxi-column>
  <dxi-column
    dataField="BirthDate"
    dataType="date"
    [editorOptions]="editorOptions"
  ></dxi-column>
</dx-data-grid>
